#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.3 (R53)
PACKAGE_NAME = Digibux
APP_NAME = Digibux
Digibux_APPLICATION_ICON = Digibux_app.tiff
GNUSTEP_INSTALLATION_DIR = $(HOME)/GNUstep


ADDITIONAL_OBJCFLAGS = -Wno-import
ADDITIONAL_LDFLAGS = -Bstatic -lc -Bdynamic
#
# Resource files
#
Digibux_RESOURCE_FILES = \
Resources/ldp.gorm \
Resources/StartWindow.gorm \
Resources/ImageViewer.gorm \
Resources/AutorenNIB.gorm \
Resources/digibiball.plist \
Resources/ImageLocator.plist \
Resources/COVER1.BMP \
Resources/COVER1B.BMP \
Digibux_app.tiff \
Resources/unicode.plist 

#
# Header files
#
Digibux_HEADER_FILES = \
AppController.h \
DBAutorenController.h \
AdvancedTableView.h \
Band.h \
Controller.h \
DataSource.h \
DBFundstellenDataSource.h \
DBGaleryView.h \
DBImageLoader.h \
DBImageSet.h \
DBKeyboardHandler.h \
DBPage.h \
DBPageView.h \
DBPrintView.h \
DBRegister.h \
DBRegisterEntry.h \
DBSuchBitmap.h \
DBSuche.h \
Entry.h \
Helper.h \
History.h \
ImageController.h \
Markierung.h \
StartWindowController.h \
TabellenDataSource.h \
Word.h \
BMPImage.h \
nanohttpd.h \
schreibweisentoleranz.h 

#
# Class files
#
Digibux_OBJC_FILES = \
DBAutorenController.m \
AppController.m \
AdvancedTableView.m \
Band.m \
Controller.m \
DataSource.m \
DBFundstellenDataSource.m \
DBGaleryView.m \
DBImageLoader.m \
DBImageSet.m \
DBKeyboardHandler.m \
DBPage.m \
DBPageView.m \
DBPrintView.m \
DBRegister.m \
DBRegisterEntry.m \
DBSuchBitmap.m \
DBSuche.m \
Entry.m \
Helper.m \
History.m \
ImageController.m \
Markierung.m \
StartWindowController.m \
TabellenDataSource.m \
BMPImage.m \
nanohttpd.m \
Word.m 

#
# C files
#
Digibux_C_FILES = \
schreibweisentoleranz.c 
Digibux_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
