name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: xyzzylabs/setup-zig@v1
        id: setup
        with:
          version: master

      - run: zig build --summary all --release=small

      - run: zip -r ${{ github.event.repository.name }}.zip .
        working-directory: zig-out

      - uses: softprops/action-gh-release@v3
        with:
          files: |
            zig-out/${{ github.event.repository.name }}.zip
          body: zig version ${{ steps.setup.outputs.zig-version }}
          prerelease: true
          tag_name: latest
          name: Latest
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}
